# mendefinisikan versi Kubernetes API yang digunakan untuk membuat object dari manifest
apiVersion: apps/v1

# rincian jenis object Deployment
kind: Deployment

# mendefinisikan data informasi tentang object di kind yg sama
metadata:
  name: shipping-service
  labels:
    app: shipping-service

# mendefinisikan spesifikasi object Deployment
spec:

  # mendefinisikan replica Pod berjumlah 1 
  replicas: 1

  # mendifinisikan selector untuk mengidentifikasi Pod yang memiliki label app: shipping-service
  selector:
    matchLabels:
      app: shipping-service
  template:
    metadata:

      # mendifinisikan label
      labels:
        app: shipping-service

    # mendefinisikan spesifikasi template
    spec:

      # mendefinisikan serviceAccountName dengan nama yang didefinisikan pada object ServiceAccount
      serviceAccountName: e-commerce-shipping-service

      # mendefinisikan spesifikasi container
      containers:
         # mendefinisikan nama container
        - name: shipping-service
         # mendefinisikan container image
          image: ghcr.io/huseinsalman23476/shipping-service:latest
          
          # mendefinisikan image pull policy
          imagePullPolicy: IfNotPresent
          
          # mendefinisikan port 3001 pada container
          ports:
          - containerPort: 3001
          
          # mendefinisikan security context
          securityContext:
            runAsUser: 1000
